version: '3.7'

services:
  nginx:
    container_name: pypiserver-nginx
    hostname: nginx
    image: nginx:1.18.0-alpine
    privileged: true
    networks: 
      pypiserver_net:
        ipv4_address: 192.168.41.2
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pypimanager-nginx/conf:/etc/nginx
      - ./pypimanager-nginx/cache:/data/nginx/cache
      - ./pypimanager-nginx/logs:/var/log/nginx
      - ./pypiserver/packages:/data/packages
  pypi-server:
    container_name: pypiserver
    image: pypiserver/pypiserver:v1.4.2
    privileged: true
    networks: 
      pypiserver_net:
        ipv4_address: 192.168.41.3
    # ports:
    #   - 8081:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pypiserver/packages:/data/packages
      - ./pypiserver/logs:/logs
    # command: -P /data/auth/.htpasswd -a update,download,list /data/packages
    command: -v --log-file=/logs/pypiserver.log -P . -a . /data/packages
    restart: always

networks: 
  pypiserver_net:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 192.168.41.0/16